export default {
  'login_success_msg': 'You just logged in successfully.',
  'signup_failed_msg1': 'Username field is required.',
  'signup_failed_msg2': 'Email field is required.',
  'signup_failed_msg3': 'Password field is required.',
  'signup_failed_msg4': 'Please confirm your password.',
  'signup_failed_msg5': 'Password confirm is failed. Please try again.',
  'signup_failed_msg6': 'Please tick when you agree our terms of service.',
  'bet_err_msg1': 'You can bet after you log in.',
  'wallet_err_msg': 'Please top-up your wallet, as the bet exceeds your balance.',
  'disconnect_err_msg': 'You are disconnected now. Please check your network status.',
  'disconnect_err_msg1': 'Network Connection Error',
  'betting_method_err_msg': 'You cannot change the betting method unless you terminate the current betting operation.',
  'coinslack_msg': 'Your balance is insufficient. You can\'t withdraw now.',
  'withdraw_address_err_msg': 'Withdrawal Address is required.',
  'withdraw_amount_err_msg': 'The withdrawal amount should always be greater than zero.',
  'withdraw_request_success': 'Your withdrawal request has been carried out successfully. Please wait for the manager to make the withdrawal.',
  'withdraw_confirm_success': 'The withdrawal request is performed.',
  'withdrawCheck': 'There\'s a withdrawal request that hasn\'t been processed yet. Check it out.',
  'profile_username_change_success': 'Your profile username is changed successfully.',
  'profile_useremail_change_success': 'Your profile email is changed successfully.',
  'profile_password_err_msg1': 'You should input your old password.',
  'profile_password_err_msg2': 'You should input your new password.',
  'profile_password_err_msg3': 'Please confirm your new password.',
  'profile_password_change_success': 'Your new password is changed successfully.',
  'profile_avatar_change_success': 'Your avatar is changed successfully.',
  'admin_reset_password_err': 'Please confirm new password.',
  'admin_reset_password_success': 'New password is reset successfully.',
  'forgot_password_required': 'You should fill email if you reset your password.'
}
